wasedatime/wasedatime-web

client/package-lock.json, client/package.json, client/src/js/components/syllabus/CourseItem.js, client/src/js/components/timetable/CourseAndPrefItem.js, client/src/js/containers/ModalContainer.js, client/src/setupProxy.js
Update the client to create react app 2.0.5
=> Update to create react app 2.0.5

README.md
README.md: Update installing section
=> README.md: Update installing section

public/sitemap.xml, src/js/components/CoronaInfo.js, src/js/components/Footer.js
add coronavirus info page to sitemap
=> update sitemap.xml; fix: increment initial date when fetching corona info

src/js/components/courseInfo/CourseInfo.js
Extend course key to 12 digit; show same reviews of courses with same instructor & same first 10 digits of courseKey
=> Extend course key to 12 digit; show same reviews of courses with same instructor & same first 10 digits of courseKey

public/sw.js, src/serviceWorkerRegistration.js
* log sw registration
* laod single course if school syllabus not exists in local
* Feature/about us gu (#136)
* 20201229 2210
* Attempt to improve font-size of tabs
* put tabs in at center
* adjust tabs' size
* our mission content
* our mission content v1
* ourmission image
* our mission page content
* our member page
* our member page
* our team content
* members page
* members page flex
* wechat icon
* add more members
* translation
* translation
* fix header bug
* more members
* 111
* fix translation error
* for first deploy
* Move files to aboutUs folder; remove unused variables
Co-authored-by: Hu Yong Hao <mlapenang1998@gmail.com>
* Remove unused pic
* Adjust mobile nav to display AboutUs link properly
* remove unused var
* skip waiting & reload after service worker got updated
* …
=> Fix service worker not updated error (#143)

.gitmodules, blog/package-lock.json, blog/src/component/BlogIndex.tsx, blog/src/component/CareerArticles.tsx, blog/src/styles/styles.css, career/package-lock.json, root/src/styles/index.css, syllabus/src/components/milestone/CJL.tsx, syllabus/src/components/milestone/PSE.tsx, syllabus/src/components/milestone/Rikou.tsx, syllabus/src/components/milestone/SILS.tsx, syllabus/src/components/milestone/SSS.tsx, syllabus/src/containers/SyllabusContainer.tsx
- Adjust feeds layout
- Add submodule for uploading feeds
=> Release: Adjust feeds layout & add submodule

blog/src/component/CareerArticles.tsx
=> fix: adjust feed style (title & bold text)

syllabus/src/components/courseInfo/CourseInfo.tsx, syllabus/src/containers/SyllabusContainer.tsx
=> fix: prevent course item expanded horizontally on clicked

feeds/.eslintrc, feeds/components/FeedLink.tsx, feeds/package.json, feeds/pages/_app.tsx
=> fix: remove babel parser from eslintrc & env var isDev from Feeds

feeds/next.config.js
=> fix: set Feeds build dir to dist

feeds/JSX.d.ts, feeds/components/FeedLink.tsx, feeds/pages/[lang]/[feed].tsx, feeds/pages/_app.tsx, feeds/pages/_document.tsx, feeds/styles/feed.css, feeds/typings.d.ts
We implement AMP in our feeds for a better SEO
- Initialize AMP only for each feed's page
- Fix compilation error
=> AMP implementation in Feeds

root/.npmrc
=> Update BIT_TOKEN and remove the value from the project

syllabus/src/components/labs/Lab.tsx, syllabus/src/components/labs/Labs.tsx, syllabus/src/components/labs/SchoolMajorSelector.tsx
=> Fix mobile UI of Labs page

syllabus/src/components/labs/Labs.tsx, syllabus/src/components/labs/SchoolMajorSelector.tsx
=> Adjust height and bottom padding of Labs page

syllabus/src/components/labs/Labs.tsx, syllabus/src/constants/locales/en/translation.json, syllabus/src/constants/locales/ja/translation.json
=> Add special thank message on Labs

campus/package.json, campus/pnpm-lock.yaml, feeds/package.json, feeds/pnpm-lock.yaml, root/package.json, root/pnpm-lock.yaml, syllabus/package.json, syllabus/pnpm-lock.yaml, syllabus/src/components/timetable/ColorSelector.tsx, syllabus/src/components/timetable/CourseAndPrefItem.tsx, syllabus/src/components/timetable/Timetable.tsx
Dark theme for part of Timetable
- Pro tips dark mode:
- Course colors selector popup
=> Feature: Timetable dark theme

campus/package.json, campus/pnpm-lock.yaml, campus/vite.config.ts, root/package.json, root/pnpm-lock.yaml, root/src/index.html, root/vite.config.ts, syllabus/package.json, syllabus/pnpm-lock.yaml, syllabus/vite.config.ts
=> Feature: parsing env var in Vite

root/package.json, root/pnpm-lock.yaml, root/src/index.html, root/src/sw.js, root/src/sw.ts, root/src/wasedatime-root-config.ts, root/tsconfig.json, root/vite.config.ts
=> Fix service worker to enable it to replace old one

root/src/index.html
=> add script-src-elem to Content Security Policy

root/src/index.ejs
=> add blob to csp

feeds/package.json, feeds/pnpm-lock.yaml, syllabus/package.json, syllabus/pnpm-lock.yaml
=> fix: install missing packages

root/src/index.ejs
=> allow all in csp default-src

root/src/index.ejs
=> allow all in csp

feeds/constants/types.ts, feeds/pages/[lang]/index.tsx
=> fix: Link to Feed after filtering

forum/src/components/BoardMenu.tsx, forum/src/components/FilterMenu.tsx, forum/src/components/TagsModal.tsx, forum/src/recoil/atom.d.ts, forum/src/recoil/atoms.ts, forum/src/root.component.tsx
=> Recoil installation and defining global states

apps/forum/package.json, apps/forum/pnpm-lock.yaml, apps/forum/src/components/CommentForm.tsx, apps/forum/src/components/CreateThread.tsx, apps/forum/src/components/SchoolFilterForm.tsx, apps/forum/src/components/icons/CloseIcon.tsx, apps/forum/src/components/icons/SendIcon.tsx, apps/forum/src/root.component.tsx
Ask user to login before opening new thread form / submitting new thread
We only allow authenticated users to create threads
Open new thread form with/without login
https://user-images.githubusercontent.com/43674499/214816053-5346f894-a193-4433-84d2-210c207f39d6.mov
=> User auth for Forum

.github/actions/microapp/action.yml, campus/package.json, campus/pnpm-lock.yaml, career/pnpm-lock.yaml, feeds/pnpm-lock.yaml, root/package.json, root/pnpm-lock.yaml, root/src/index.html, syllabus/pnpm-lock.yaml
=> fix: update July 2023 feeds

apps/campus/pnpm-lock.yaml, apps/career/pnpm-lock.yaml, apps/feeds/pnpm-lock.yaml, apps/forum/pnpm-lock.yaml, apps/forum/src/components/App.tsx, apps/forum/src/components/Board.tsx, apps/forum/src/components/BoardMenu.tsx, apps/forum/src/components/CommentForm.tsx, apps/forum/src/components/CreateThread.tsx, apps/forum/src/components/FilterMenu.tsx, apps/forum/src/components/Forum.tsx, apps/forum/src/components/Home.tsx, apps/forum/src/components/SchoolFilterForm.tsx, apps/forum/src/components/Thread.tsx, apps/forum/src/components/ThreadBlock.tsx, apps/forum/src/constants/boards.json, apps/forum/src/recoil/atoms.ts, apps/forum/src/utils/auth.ts, apps/forum/src/utils/filter.ts, apps/root/pnpm-lock.yaml, apps/syllabus/pnpm-lock.yaml, packages/eslint-config-custom/pnpm-lock.yaml, packages/ui/pnpm-lock.yaml
=> feat: forum restructuring 

apps/forum/src/components/App.tsx, apps/forum/src/components/Board.tsx, apps/forum/src/components/BoardMenu.tsx, apps/forum/src/components/Comment.tsx, apps/forum/src/components/CommentForm.tsx, apps/forum/src/components/CreateThread.tsx, apps/forum/src/components/FilterMenu.tsx, apps/forum/src/components/Thread.tsx, apps/forum/src/components/ThreadBlock.tsx, apps/forum/src/components/common/SchoolFilter.tsx, apps/forum/src/components/icons/SendIcon.tsx, apps/forum/src/types/thread.ts, apps/forum/src/utils/get-school-icon-path.ts
Changed the current event listener to infinite scroll. This is so much more easier.
=> feat: enlarging the fontsize of forums. Currently it was just too small

apps/forum/pnpm-lock.yaml, apps/forum/src/components/Comment.tsx, apps/forum/src/components/CommentForm.tsx, apps/forum/src/components/CreateThread.tsx, apps/forum/src/components/Thread.tsx, apps/forum/src/components/ThreadBlock.tsx, apps/forum/src/types/thread.ts, packages/eslint-config-custom/pnpm-lock.yaml, packages/ui/pnpm-lock.yaml, pnpm-lock.yaml
=> feat: added comment count

apps/forum/src/components/Comment.tsx, apps/forum/src/components/CreateThread.tsx, apps/forum/src/components/Thread.tsx, apps/forum/src/components/ThreadBlock.tsx, apps/forum/src/types/thread.ts, apps/forum/src/types/threadPayload.ts
=> feat: adding images to forums

apps/forum/src/components/Thread.tsx, apps/root/src/components/user/RedirectPage.tsx
=> fix: fixing idToken retreval function

apps/feeds/next.config.js, apps/feeds/tsconfig.json, apps/forum/src/components/App.tsx, apps/forum/src/components/Board.tsx, apps/forum/src/components/Comment.tsx, apps/forum/src/components/CreateThread.tsx, apps/forum/src/components/Thread.tsx, apps/forum/src/components/ThreadBlock.tsx, apps/forum/src/utils/timeFormatter.tsx
=> feat: forum time formating with page thread formating

.github/workflows/deploy.yml, apps/forum/src/utils/getDate.ts, apps/forum/src/utils/storeDate.ts, apps/root/src/components/frame/Nav.tsx, apps/root/src/utils/getDate.ts, apps/root/src/utils/shouldCallApi.ts
=> fix: fixing the forum date extract logic

apps/career/src/components/joblist/JobCard.tsx, apps/career/src/components/joblist/JobCardFooter.tsx, apps/career/src/components/joblist/Joblist.tsx, apps/career/src/root.component.tsx, apps/career/tsconfig.json, apps/career/vite.config.ts
=> fix: hotfix on vite configuration

apps/career/src/App.tsx, apps/career/src/components/common/AgreeModal.tsx, apps/career/src/components/common/Header.tsx, apps/career/src/components/common/Modal.tsx, apps/career/src/components/jobdetail/JobContent.tsx, apps/career/src/components/jobdetail/JobOverview.tsx, apps/career/src/components/jobdetail/Jobdetail.tsx, apps/career/src/components/joblist/JobCard.tsx, apps/career/src/components/joblist/Joblist.tsx, apps/career/src/components/joblist/ProfileModal.tsx, apps/career/src/utils/postApplication.ts, apps/forum/src/components/common/Header.tsx
=> feat: career post application and agreement modal

apps/career/src/components/jobdetail/JobContent.tsx
=> feat: text size to section title of job content

apps/career/src/App.tsx, apps/career/src/components/jobdetail/JobContent.tsx, apps/career/src/components/jobdetail/JobOverview.tsx, apps/career/src/components/jobdetail/Jobdetail.tsx, apps/career/src/components/joblist/JobCard.tsx, apps/career/src/components/joblist/Joblist.tsx, apps/career/src/components/joblist/PostRegisterProfile.tsx, apps/career/src/components/joblist/ProfileModal.tsx, apps/career/src/constants/dropdownOptions.ts, apps/career/src/styles/main.css, apps/career/src/types/careerComponentProps.ts, apps/career/src/types/job.ts, apps/career/src/utils/postApplication.ts, apps/forum/src/components/ThreadBlock.tsx
=> feat: finishing up careers page

apps/career/src/App.tsx, apps/career/src/components/common/AgreeModal.tsx, apps/career/src/components/joblist/Joblist.tsx, apps/career/src/components/joblist/PreRegisterProfile.tsx, apps/career/src/components/joblist/ProfileModal.tsx, apps/career/src/types/careerComponentProps.ts, apps/career/src/types/profileComponentProps.ts
=> fix: hotfix for career page language selection and profile registration

apps/root/src/App.tsx, apps/root/src/components/CommercialDisclosure.tsx, apps/root/src/components/frame/OtherLinks.tsx, packages/ui/src/constants/locales/en.json, packages/ui/src/constants/locales/ja.json
=> feat: commercial disclosure page

apps/career/src/components/common/SchoolFilter.tsx, apps/career/src/components/joblist/ProfileModal.tsx
=> feat: ensuring school input and styling for profile modal
